### PR TITLE
Fix entity virtual props recursion

### LINKED ISSUE #1602: CustomProperties behavior recursion problem
There is a recursion problem in ```CustomPropertiesBehavior::isFieldSet($entity, $field)```

Suppose you have an entity virtual getter method like this: 

```php
    protected function _getMyProperty()
    {
        // ....
        $this->getTable()->loadInto($this, ['RelationName']);
       // ... 
     }
```

If `CustomProperties` behavior is used by entity's table class in `isFieldSet($entity, $field)` method this line

```php
$allProperties = $entity->toArray();
``` 
will cause a recursion since the same virtual method is called again.

### PR DESCRIPTION
**Pull request by stefanorosanelli**
This PR fixes #1602 a potential recursion problem in entities.

In a virtual getter or setter if you call for instance:

```
 $this->getTable()->loadInto($this, ['MyRelation']);
```

to retrieve related entities, will cause internally a new call on `$entity->toArray()` via `CustomPropertiesBehavior::isFieldSet()` that will call the above virtual method again...

### CODE REVIEW

File: plugins/BEdita/Core/src/Model/Behavior/CustomPropertiesBehavior.php [hunk 1]
```diff
@@ -212,15 +212,12 @@ protected function isFieldSet($entity, $field)
...
         $allProperties = $entity;
         if ($entity instanceof EntityInterface) {
-            $hidden = $entity->getHidden();
-            try {
-                $entity->setHidden([]);
-                $allProperties = $entity->toArray();
-            } finally {
-                $entity->setHidden($hidden);
-            }
+            $allProperties = array_flip(array_merge(
```
Comment (batopa) [inline plugins/BEdita/Core/src/Model/Behavior/CustomPropertiesBehavior.php]: But in this way we take all entity properties not just those set. Is it correct?

**Review by batopa — APPROVED** [review]
