### PR TITLE
[#1603] feat: logged user cannot trash his own user 

### LINKED ISSUE #1603: Trash logged user
A trash request like `DELETE /users/{id}` where `id` is the current logged user should fail.

Instead it is working just fine... :scream_cat: 

A new `BadRequest` or `Forbidden` exception should be rased with message like: `Logged users cannot delete their own account`

### PR DESCRIPTION
**Pull request by didoda**
This PR fixes #1603

### CODE REVIEW

**Review by stefanorosanelli — APPROVED** [review]

File: plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php [hunk 1]
```diff
@@ -285,6 +285,24 @@ public function testSoftDeleteAdminUser()
         $this->Users->save($user);
     }
 
+    /**
+     * Test soft delete logged user
+     *
+     * @return void
+     *
+     * @expectedException \Cake\Network\Exception\BadRequestException
+     * @expectedExceptionCode 403
```
Comment (stefanorosanelli) [inline plugins/BEdita/Core/tests/TestCase/Model/Table/UsersTableTest.php]: should be `400` see Travis failure...

**Review by stefanorosanelli — CHANGES_REQUESTED** [review]

**Comment by stefanorosanelli** [comment]
Not covered in #1603, but also necessary I guess, same check should be done in
* permanent removal `DELETE /trash/{id}`
* restore `PATCH /trash/{id}`

@didoda @batopa @fquffio ?

**Review by stefanorosanelli — APPROVED** [review]
