### PR TITLE
Command `project_model` skips saving category if already present in database

### LINKED ISSUE #2092: Project model update categories override database categories
### Expected behavior

When database has categories (with or without translations), if we launch `bin/cake project_model`, categories already present in database won't change, even if they are in `categories` of `project_model.json`.

### Actual behavior

When database has categories (with or without translations), if we launch `bin/cake project_model`, categories already present in database change, if they are in `categories` of `project_model.json`: categories are restored to values in `project_model.json`.

### Steps to reproduce the behavior

1. Prepare a `project_model.json` with some categories
2. Launch `bin/cake project_model`
3. Edit some categories in database (i.e. change labels)
4. Launch `bin/cake project_model`
5. Verify: categories labels are restored to values in `project_model.json

### PR DESCRIPTION
**Pull request by didoda**
This PR fixes https://github.com/bedita/bedita/issues/2092

Project model command skip update categories if already present in database.

### CODE REVIEW

File: plugins/BEdita/Core/src/Utility/ProjectModel.php [hunk 1]
```diff
@@ -231,12 +231,32 @@ public static function diff(array $project): array
...
+     * @param array $update Update array
+     * @return void
+     */
+    public static function categoriesToUpdate(array &$update): void
+    {
+        if (!Hash::check($update, 'categories.{n}.name')) {
+            return;
+        }
+        $names = (array)Hash::extract($update['categories'], '{n}.name');
+        $found = TableRegistry::getTableLocator()->get('Categories')->find()->where(['name IN' => $names])->toArray();
```
Comment (batopa) [inline plugins/BEdita/Core/src/Utility/ProjectModel.php]: We need to search `name` for object type because the same category name could be used for different object types

**Review by batopa — APPROVED** [review]
