### PR TITLE
#1136 feat: shell relation check and fix more details and enhance fixes

### LINKED ISSUE #1136: Shell relation check and fix: more details + enhance fixes
Shell relation provides a method to verify relation data consistency.
Some inconsistencies are not shown (i.e.: object_relations records refer to a type not related to the relation).
Method check should show:
 - number of object_relations that refer to the `wrong` object types (= all types related count - model related types count)
 - details of number of unexpected per-type relations
Issues could be shown like:
 - `allowed types [left]->'<relation>'->[right]: <count> => should be <number expected>`
 - `allowed types [right]->'<relation inverse>'->[left]: <count> => should be <number expected>`
 - `all types [left]->'<relation>'->[right]: <count> => should be <number expected>`
 - `all types [right]->'<relation inverse>'->[left]: <count> => should be <number expected>`

### PR DESCRIPTION
**Pull request by didoda**
This fixes #1136

### CODE REVIEW

File: bedita-app/models/business/relation_check.php [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+ * version 3 along with BEdita (see LICENSE.LGPL).
+ * If not, see <http://gnu.org/licenses/lgpl-3.0.html>.
+ * 
+ *------------------------------------------------------------------->8-----
+ */
+
+/**
+ * Class that provides relation check utility methods
+ * 
+ * @version			$Revision$
```
Comment (stefanorosanelli) [inline bedita-app/models/business/relation_check.php]: These old annotations / tags (from `@versions` to `$Id$`) are not needed anymore

Made sense in SVN era :wink:

File: bedita-app/models/business/relation_repair.php [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+ * 
+ *------------------------------------------------------------------->8-----
+ */
+
+App::import('Component', 'Transaction');
+
+/**
+ * Class that provides relation repair utility methods
+ * 
+ * @version			$Revision$
```
Comment (stefanorosanelli) [inline bedita-app/models/business/relation_repair.php]: same here on annotations / tags....

File: bedita-app/models/business/relation_check.php [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+            return false;
+        } else {
+            $messageBuffer[] = "$info [left]->'$relationName'->[right]: $count1";
+            $messageBuffer[] = "$info [right]->'$relationInverse'->[left]: $count2 => should be $count1";
+            return false;
+        }
+        return true;
+    }
+}
+?>
```
Comment (stefanorosanelli) [inline bedita-app/models/business/relation_check.php]: PHP files should ent with empty new line
http://www.php-fig.org/psr/psr-2/#files

File: bedita-app/models/business/relation_check.php [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+ * @modifiedby 		$LastChangedBy$
+ * @lastmodified	$LastChangedDate$
+ * 
+ * $Id$
+ */
+class RelationCheck extends BEAppModel
+{
+    public $useTable = false;
+
+    public function checkRelation($relationName, &$messageBuffer) {
```
Comment (stefanorosanelli) [inline bedita-app/models/business/relation_check.php]: doc block needed
