### PR TITLE
Fix error 500 on post/patch/delete without authenticated user

### LINKED ISSUE #1141: Error 500 on POST object without auth
Trying to create an object with a POST without `Authorization` header we get:

 * with `debug` on - an error 500 response with raw **An Internal Server Error Occurred** text and "text/html" content type (no JSON), while in `error.log` we have 
```
2017-03-14 10:11:03 Error: [RuntimeException] You cannot call all() on a non-select query. Use execute() instead.
```
 
* with `debug` off - an error 500 response like this 
```json
{
   "error": {
     "status":"500",
      "title":"An Internal Error Has Occurred."
  }
}
```
while in error log we have 
```
2017-03-14 10:14:47 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_by' cannot be null
```

There's something wrong with our exception renderer
Also response in this case should be 401 not 500

Are these cases not covered by our test suite?

### PR DESCRIPTION
**Pull request by batopa**
This PR resolves #1141

### CODE REVIEW

File: plugins/BEdita/API/src/Event/CommonEventHandler.php [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+     *
+     * @param \Cake\Event\Event $event The event object
+     * @param \Cake\Http\MiddlewareQueue $middleware The middleware queue
+     * @return void
+     * @see \BEdita\API\Middleware\CorsMiddleware to more info on CORS configuration
+     */
+    public function buildMiddlewareStack(Event $event, MiddlewareQueue $middleware)
+    {
+        $middleware->insertAfter(
+            'Cake\Error\Middleware\ErrorHandlerMiddleware',
```
Comment (fquffio) [inline plugins/BEdita/API/src/Event/CommonEventHandler.php:67]: As a rule of thumb, I generally prefer `ErrorHandlerMiddleware::class` instead of a string containing the FQNS.

It yields the very same result, so it makes no difference, but it generally makes it easier to spot usages of a particular class in IDEs and code analysis tools. Should ever `ErrorHandlerMiddleware` class become deprecated, for instance, it would make it easier for us to remove the deprecated component.

**Review by fquffio — APPROVED** [review]

**Review by stefanorosanelli — APPROVED** [review]
