### PR TITLE
Fix multiple issues with Folders' relationships #1471

### LINKED ISSUE #1471: Set children fail + set parent allowed types
Two problems on folder relationships actions:

1. setting `children` via POST fails 
1. set parent via PATCH is allowed for non-folder objects

See this compare as reference on `stefanorosanelli:fix/v4/children-parent-fail`
https://github.com/bedita/bedita/compare/4-cactus...stefanorosanelli:fix/v4/children-parent-fail

1. `patch conflict` test passes with 200 instead of failing with 409
1. `testSetParent` is OK
1. `testSetChildren` fails

### PR DESCRIPTION
**Pull request by fquffio**
This PR fixes #1471 by adding the suggested tests and fixing some strange behaviours when linking parents and children together.

### CODE REVIEW

File: plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php [hunk 1]
```diff
@@ -518,20 +543,91 @@ public function setRelationshipsAllowedMethodsProvider()
      *
      * @param int $expected The expected HTTP status code.
      * @param string $method The http method.
-     * @param array|null $data Payload to use for the request.
+     * @param array $data Payload to use for the request.
      * @return void
+     * @throws \Exception
```
Comment (batopa) [inline plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php]: [minor] Not really :smile_cat:

**Review by stefanorosanelli — APPROVED** [review]

File: plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php (hunk 1 above)
Comment (fquffio) [reply plugins/BEdita/API/tests/TestCase/Controller/FoldersControllerTest.php]: Yes, you're right… 😞 It's PHPStorm that keeps on complaining about the lack of this annotation because `IntegrationTestCase::_sendRequest()` method's docblock includes `@throws \Exception`. 😡

**Review by batopa — APPROVED** [review]
