### PR TITLE
JSON API `sparse fieldsets`

### LINKED ISSUE #1393: Sparse fieldsets with `fields` query parameter
This part of the spec has to be implemented http://jsonapi.org/format/#fetching-sparse-fieldsets

We have a custom `fields` selection https://docs.bedita.net/en/latest/endpoints/parameters.html#field-selection - that is our spec extension

In fact we get a nice 500 Error trying with a simple URL like `/objects?fields[users]=title` 
```
2017-12-07 09:02:44 Error: [TypeError] Argument 3 passed to BEdita\API\Utility\JsonApi::formatData() must be of the type array, null given, called in /var/www/bedita4/plugins/BEdita/API/src/View/JsonApiView.php on line 47 in /var/www/bedita4/plugins/BEdita/API/src/Utility/JsonApi.php on line 38
Request URL: /objects?fields%5Busers%5D=title
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/bedita4/plugins/BEdita/API/src/View/JsonApiView.php(47): BEdita\API\Utility\JsonApi::formatData(Object(Cake\Datasource\ResultSetDecorator), 0, NULL, Array)
#1 /var/www/bedita4/vendor/cakephp/cakephp/src/View/JsonView.php(136): BEdita\API\View\JsonApiView->_dataToSerialize(Array)
#2 /var/www/bedita4/vendor/cakephp/cakephp/src/View/SerializedView.php(98): Cake\View\JsonView->_serialize(Array)
```

### PR DESCRIPTION
**Pull request by stefanorosanelli**
This PR fixes #1393 

`filter` query string has been updated to support queries like:
 `/objects?fields[documents]=title&fields[locations]=description`

current common `filter` queries are still valid:
 `/documents?fields=title,description`

### CODE REVIEW

File: plugins/BEdita/API/src/View/JsonApiView.php [hunk 1]
```diff
@@ -73,4 +73,27 @@ protected function _dataToSerialize($serialize = true)
...
+     * See http://jsonapi.org/format/#fetching-sparse-fieldsets
+     *
+     * @return array Formatted `fields` associative array
+     */
+    protected function parseFieldsQuery()
+    {
+        if (empty($this->viewVars['_fields'])) {
+            return [];
+        }
+        if (!empty($this->viewVars['_fields']) && is_string($this->viewVars['_fields'])) {
```
Comment (didoda) [inline plugins/BEdita/API/src/View/JsonApiView.php]: first condition not necessary, because of previous `if`

**Review by batopa — APPROVED** [review]

File: plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiTraitTest.php [hunk 2]
```diff
@@ -469,7 +485,7 @@ public function jsonApiSerializeProvider()
      * @covers ::setFields()
      * @dataProvider jsonApiSerializeProvider()
      */
-    public function testJsonApiSerialize($excludedKeys, $options)
+    public function testJsonApiSerialize($excludedKeys, $options, $fields = null)
```
Comment (fquffio) [inline plugins/BEdita/Core/tests/TestCase/Model/Entity/JsonApiTraitTest.php:490]: [minor] Missing `@param array|null $fields ...` annotation in docblock above.

**Review by fquffio — APPROVED** [review]

**Review by didoda — APPROVED** [review]
